/*
**
** File: cf_external_functions.h
** This file is automatically generated by the
** chain flow assembler
** Build Time: 2018-10-01 20:54:07.064402  
**
*/

#ifndef _EXTERNAL_FUNCTIONS_H_
#define _EXTERNAL_FUNCTIONS_H_ 

#include "chain_flow_support.h" 
#include "cf_events.h"
/*
This is the symbolic definitions of the chains
*/



#define  initialization   0
#define  feed_watch_dog   1
#define  sampling_task   2
#define  output_task   3



/*
This is the symbolic definitions of the links for chain initialization
*/
#define  initialization_0   0
#define  initialization_1   1
#define  initialization_2   2
#define  initialization_3   3



/*
This is the symbolic definitions of the links for chain feed_watch_dog
*/
#define  feed_watch_dog_0   0
#define  feed_watch_dog_1   1
#define  feed_watch_dog_2   2



/*
This is the symbolic definitions of the links for chain sampling_task
*/
#define  sampling_task_0   0
#define  sampling_task_1   1
#define  sampling_task_2   2



/*
This is the symbolic definitions of the links for chain output_task
*/
#define  output_task_0   0
#define  output_task_1   1
#define  output_task_2   2



int app_input_sample_inputs(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int pat_watch_dog(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int wait_for_mqtt_connect(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int add_watch_dog(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int app_input_output_values(CHAIN_FLOW_HANDLE *cf, unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);






#endif
