/*
**
** File: cf_external_functions.h
** This file is automatically generated by the
** chain flow assembler
** Build Time: 2018-09-29 10:24:46.809000  
**
*/

#ifndef _EXTERNAL_FUNCTIONS_H_
#define _EXTERNAL_FUNCTIONS_H_ 

#include "cf_chain_flow_support.h" 
#include "cf_events.h"
/*
This is the symbolic definitions of the chains
*/



#define  initialization   0
#define  feed_watch_dog   1
#define  minute_tick_chain   2



/*
This is the symbolic definitions of the links for chain initialization
*/
#define  initialization_0   0
#define  initialization_1   1
#define  initialization_2   2



/*
This is the symbolic definitions of the links for chain feed_watch_dog
*/
#define  feed_watch_dog_0   0
#define  feed_watch_dog_1   1
#define  feed_watch_dog_2   2



/*
This is the symbolic definitions of the links for chain minute_tick_chain
*/
#define  minute_tick_chain_0   0
#define  minute_tick_chain_1   1



int pat_watch_dog(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int sample_switches(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int add_watch_dog(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int setup_gpio(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);






#endif
